### ISSUE TITLE
Debug info is insufficient when local variable has larger alignment.

### ISSUE THREAD

**Issue by ytlin101** [riscv/riscv-gcc#191]
When testing on gdb testsuite using rv32e, we observe local variables with
larger alignment may not be accessed correctly.

Here is a case from gdb.mi category.
In this case, debug info for the local variable 'ldouble' says that
its address can be got from $a5. But $a5 may be changed after the live
of 'ldouble' ends.

Is it possible to locate 'ldouble' using more complex expression related to fp or sp?

# Here is the step to reproduce it.
source can be got from binutils-gdb/gdb/testsuite/gdb.mi/var-cmd.c
or
unofficial github link
https://github.com/bminor/binutils-gdb/blob/master/gdb/testsuite/gdb.mi/var-cmd.c

$ riscv32-unknown-elf-gcc -march=rv32e -mabi=ilp32e -g -fno-omit-frame-pointer -o mi-var-cmd var-cmd.c
$ riscv32-unknown-elf-gdb mi-var-cmd
(gdb) target sim
Connected to the simulator.
(gdb) lo
...
(gdb) b 172
Breakpoint 1 at 0x102b4: file var-cmd.c, line 172.
(gdb) r
...

Breakpoint 1, do_locals_tests () at var-cmd.c:172
172       lsimple.integer = 255;
(gdb) p ldouble		<== ldouble is correct
$3 = 5.4985482818281719
(gdb) n
173       lsimple.unsigned_integer = 4321;
(gdb) p ldouble
$4 = 0			<== ldouble is changed unexpectedly

or
another senario, this tries to get the local variable from previous frame

(gdb) b 172
Breakpoint 1 at 0x102b4: file var-cmd.c, line 172.
(gdb) r
...

Breakpoint 1, do_locals_tests () at var-cmd.c:172
172       lsimple.integer = 255;
(gdb) p ldouble
$3 = 5.4985482818281719

(gdb) b subroutine1
(gdb) continue
Continuing.

Breakpoint 2, subroutine1 (i=4321, l=0x3fff778) at var-cmd.c:202
202       global_simple.integer = i + 3;
(gdb) bt
#0  subroutine1 (i=4321, l=0x3fff778) at var-cmd.c:202
#1  0x000102e8 in do_locals_tests () at var-cmd.c:177
#2  0x00010a9c in main (argc=1, argv=0x3fff7c4) at var-cmd.c:641
(gdb) f 1
#1  0x000102e8 in do_locals_tests () at var-cmd.c:177
177       subroutine1 (linteger, &llong);
(gdb) p ldouble
$4 = 0			<== ldouble is unexpected

--

$ riscv32-unknown-elf-objdump -Wi mi-var-cmd

 <2><1770>: Abbrev Number: 58 (DW_TAG_variable)
    <1771>   DW_AT_name        : (indirect string, offset: 0x514): ldouble
    <1775>   DW_AT_decl_file   : 1
    <1776>   DW_AT_decl_line   : 141
    <1777>   DW_AT_decl_column : 10
    <1778>   DW_AT_type        : <0x1132>
    <177c>   DW_AT_location    : 2 byte block: 7f 0     (DW_OP_breg15 (a5): 0)

**Comment by jim-wilson** [comment]
There are multiple problems here.

We don't have dedicated resources for gdb.  So anything reported against gdb is unlikely to be fixed unless gdb is crashing, or you are willing to do the work yourself, or pay someone to fix it for you.

The rve ABI says that the stack has 4-byte alignment.  But a long double requires 16 byte alignment.  So the compiler is screwed.  It has to allocate extra space and then align it.  This results in a complex expression for the address of ldouble which we currently don't have support to express in the debug info.  Yes, this could be fixed.  But anyone using rve is extremely unlikely to be using long double types, so the amount of work to fix is greater than the benefit of doing the work.  This is incidentally why we don't have rv32ed support in the toolchain, because the stack alignment issue makes it too hard to implement to be worth the trouble.

The best long term solution here is to fix the ABI.  There are tentative plans for a new embedded ABI that will work for both rvi and rve, but development of that has been on hold for about 2 years due to lack of people to work on it.
